// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRQz4L1kCkfO4lVOO5zXzO4hEYdCjDKJE',
    appId: '1:36306452091:web:533364c6e3c69fd43eecde',
    messagingSenderId: '36306452091',
    projectId: 'toaster-378805',
    authDomain: 'toaster-378805.firebaseapp.com',
    storageBucket: 'toaster-378805.appspot.com',
    measurementId: 'G-1RJCM3XWD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD38Ko9F3bLTDe0BGnCE7YVhwCRYqEDi90',
    appId: '1:36306452091:android:3d3bdf2beca574f23eecde',
    messagingSenderId: '36306452091',
    projectId: 'toaster-378805',
    storageBucket: 'toaster-378805.appspot.com',
  );
}
